version: '3.9'

services:
  asset_mappr_be_service:
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: ./../src
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - asset_mappr_be_service

volumes:
  static:
