# Generated by Django 4.2.1 on 2023-06-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('community', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('community_geo_id', models.IntegerField()),
                ('dob', models.DateField()),
                ('ethnicity', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='user.user')),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
